### ISSUE TITLE
Produce a Glossary of Terms

### ISSUE THREAD

**Issue by callumforrester** [bluesky/bluesky-cookbook#10]
Produce a glossary of commonly used, domain specific terms such as flyscanning. Useful place to start is the flyscanning explanation here: https://github.com/bluesky/ophyd-async/pull/113

Due to differences in terminology across facilities, some wrangling may be required to get a consistent view of the collaboration (I regret that we may have to redefine some things at Diamond using American English).

**Comment by abbiemery** [comment]
to do: Move the fly-scanning document from ophyd-async into the cookbook. see [ophyd-async 113](https://github.com/bluesky/ophyd-async/pull/113).

**Comment by stan-dot** [comment]
what is the user for this documentation?
I closed this as now there is 'a glossary' and if needed it's easy to add new terms to it if the need arises. 

The other approach would be to intentionally try to create a comprehensive encyclopedia.


all depends on who is the user: support engineers, core bluesky devs, potential adopters in other facilities? 

The idea of having yet another place for docs where everything is kept up to date has an upkeep effort cost, so I assume the use case is very necessary.
